#!/bin/bash
set -e

# Setting variables
BASE_DIR=/opt/{PACKAGE_NAME}
APP_DIR=$BASE_DIR
SETTINGS_FILE=$BASE_DIR/app_config.env

source $SETTINGS_FILE
CONFIG_DIR="~/pankosmia/${APP_SHORT_NAME}"

if [ -d "$CONFIG_DIR" ]; then
    echo "Removing prior config directory: $CONFIG_DIR"
    rm -rf "$CONFIG_DIR"
fi
