#!/bin/bash
set -e

# Iterate over user home directories
for USER_HOME in /Users/*; do
    CONFIG_DIR="$USER_HOME/pankosmia/{APP_SHORT_NAME}"
    if [ -d "$CONFIG_DIR" ]; then
        echo "Removing prior config directory: $CONFIG_DIR"
        rm -rf "$CONFIG_DIR"
    fi
done